######################################################################
# Automatically generated by qmake (2.01a) Tue Jun 10 19:48:21 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += sgbitmap.h sgfile.h sgimage.h imagetreeitem.h mainwindow.h
SOURCES += main.cpp sgbitmap.cpp sgfile.cpp sgimage.cpp imagetreeitem.cpp mainwindow.cpp
